name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run typecheck
        run: npm run typecheck
      - name: Lint and Prettier
        run: npm run lint && npm run prettier:check
      - name: Static Tests
        run: npm run static-tests
      - name: All Tests
        run: npm run test:ava
